language: php
php:
  - '7.1'

install:
  - travis_retry composer install -no
  
script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)